Update Kitodo.Production and scripts for webhook manager version
slub/ocrd_kitodo pull request #98
Opened 2023-12-20 11:44 UTC by markusweigelt

- Using current master state of Kitodo.Production
- Adjust sql examples
- Improve process dir script to use

2023-12-20 11:54 UTC, bertsky requested changes
perhaps this PR should also link to https://github.com/slub/ocrd_manager/pull/66

2023-12-20 11:54 UTC, bertsky commented on Makefile
> +	docker compose build $(SERVICES)
Where is `SERVICES` defined? 

What is it for?

2023-12-20 11:54 UTC, bertsky commented on Makefile
> +	docker compose start
If you want to **restart**, then you should name it like that.

Also, why not just use `docker compose up --build` for that?

2023-12-20 11:54 UTC, bertsky commented on Makefile
> +	docker compose down -v
Makefiles should not contain interactive stuff. What is the motivation for that?

2023-12-20 12:00 UTC, markusweigelt commented on Makefile
> +	docker compose build $(SERVICES)
It is an improvement for the development that I find very helpful for rebuilding a single service in connection with the Makefile. For example, for changes to the OCR-D monitor. The function does not restrict the previous behavior but only complements it. Using with `SERVICES=ocrd-monitor make build`

2023-12-20 12:19 UTC, markusweigelt commented on Makefile
> +	docker compose down -v
Why shouldn't there be a confirmation prompt for critical `make targets`? In my case, it has often happened that I accidentally confused `stop` with `down`.

2023-12-20 13:36 UTC, bertsky commented on Makefile
> +	docker compose start
After you rebuild, you must also recreate the container, otherwise it will just restart the (old) stopped container.

Hence `docker compose up --build $(SERVICES)`. (And I was not proposing to use that instead of a target, but as recipe for this target.)

2023-12-20 13:39 UTC, markusweigelt commented on Makefile
> +	docker compose start
In my case, Docker does this automatically and starts the new container. It also mentions briefly with "Recreating" during startup.

2023-12-20 13:41 UTC, bertsky commented on Makefile
> +	docker compose down -v
Because no-one expects to get a prompt when running make (and it won't work if you run without a tty).

By that logic, you could insert "are you sure" prompts everywhere...

2023-12-20 13:44 UTC, markusweigelt commented on Makefile
> +	docker compose down -v
> By that logic, you could insert "are you sure" prompts everywhere...

Why? With no other command is everything flattened and you have to build again. 
But ok I'll take it out and just use it locally

2023-12-20 16:50 UTC, bertsky commented on Makefile
> +	docker compose down -v
Thx

2024-01-09 11:05 UTC, markusweigelt commented
@bertsky Adjusted to the changed asynchronous behavior of OCR-D manager. Synchronous is now the default.

2024-03-01 12:19 UTC, bertsky reviewed
LGTM.

Just needs to be updated to new Manager (after https://github.com/slub/ocrd_manager/pull/66 itself is finished and merged), and one minor change may be required (see below).

2024-03-01 12:19 UTC, bertsky commented on _resources/kitodo/data/scripts/script_ocr_process_dir.sh
> +    COMMAND+=" --workflow /workflows/$WORKFLOW"
Do we know for sure that the `$WORKFLOW` path selectable on the UI is relative to the directory `MANAGER_WORKFLOWS` mounted by the Manager as volume under `/workflows`?

2024-03-01 12:19 UTC, bertsky commented on _resources/kitodo/data/scripts/script_ocr_process_dir.sh
> +    COMMAND+=" --activemq-url tcp://$MQ_HOST:$MQ_PORT?closeAsync=false --activemq-queue TaskActionQueue --async true"
Assuming you will rewrite the `--async` parameter:
```suggestion
    COMMAND+=" --activemq-url tcp://$MQ_HOST:$MQ_PORT?closeAsync=false --activemq-queue TaskActionQueue --async"
```

2024-03-01 12:19 UTC, bertsky commented on .github/workflows/makefile-ci.yml
> +      run: make test || { docker compose logs ocrd-manager; false; }
Good idea!

2024-03-01 12:52 UTC, markusweigelt commented on _resources/kitodo/data/scripts/script_ocr_process_dir.sh
> +    COMMAND+=" --workflow /workflows/$WORKFLOW"
Yes, you're right, I'll undo that. I don't really know anymore what I was thinking at that moment.

2024-03-01 12:54 UTC, markusweigelt commented on .github/workflows/makefile-ci.yml
> +      run: make test || { docker compose logs ocrd-manager; false; }
That was your idea, and I believe you even provided me with the code for it ;)

2024-03-05 08:42 UTC, bertsky commented on .github/workflows/makefile-ci.yml
> +      run: make test || { docker compose logs ocrd-manager; false; }
I wonder why it does not apply on **this PR** already, though. We should be able to see the Manager logs when `make test` fails below, shouldn't we?

2024-03-07 18:31 UTC, bertsky approved these changes

2024-03-07 19:38 UTC, bertsky commented
Wait! One bug did slip through:
https://github.com/slub/ocrd_kitodo/blob/b8a38856dc3fee1e5d45ce4ea1b1b6d834db077b/.env#L22-L23

Notice the wrong variable name for the pw?

Live this causes:
```
MongoServerError: Authentication failed.
```

2024-03-07 19:39 UTC, bertsky commented
Also fixed in https://github.com/slub/ocrd_kitodo/commit/c59b4cbd81f57b4de377b78ac641f977df2cd4c5.

2024-03-07 21:55 UTC, bertsky commented
@markusweigelt, short explanation: in trying to make this work, I noticed I do need to update the Controller (because our timeout was partially caused by glitches there, not SSH itself) _and_ added waiting for ocrd-database (because that is what surfaced on the CI as well). So I basically had to put all on one card. Hope all this is sufficient now :crossed_fingers:

2024-03-09 00:15 UTC, merged